Feature/retrigger content processing
toggle-corp/ai-chatbot-backend pull request #46
Opened 2024-12-18 05:18 UTC by sudan45

## Addresses
- https://github.com/toggle-corp/ai-chatbot-backend/issues/45
## Depends on
-  https://github.com/toggle-corp/ai-chatbot-backend/tree/project/contextual-chunks
## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)

2024-12-18 08:07 UTC, susilnem requested changes
Minor changes

2024-12-18 08:07 UTC, susilnem commented on content/admin.py
> +    def action(modeladmin, request, queryset):
```suggestion
def action(modeladmin, request, queryset):
```

2024-12-18 08:07 UTC, susilnem commented on content/admin.py
> +    actions = [action_test()]
```suggestion
    actions = [action()]
```

2024-12-18 08:07 UTC, susilnem commented on content/tasks.py
> +    except Exception:
Add a Note for catching All kind of Exception.

2024-12-18 08:45 UTC, susilnem requested changes
Minor changes

2024-12-18 08:45 UTC, susilnem commented on content/admin.py
> +        messages.add_message(request, messages.INFO, mark_safe("Successfully Re-trigger content processing! "))
```suggestion
        messages.add_message(request, messages.INFO, mark_safe("Successfully re-trigger content processing! "))
```

2024-12-18 08:45 UTC, susilnem commented on content/admin.py
> +    actions = [trigger_content_processing()]
Let's add the function inside the ContentAdmin.

2024-12-27 08:47 UTC, susilnem approved these changes

2025-04-16 09:40 UTC, sudan45 commented
- https://github.com/toggle-corp/ai-chatbot-backend/pull/96

2025-04-16 09:40 UTC, closed without merging