Project/contextual chunks
toggle-corp/ai-chatbot-backend pull request #47
Opened 2024-12-20 04:28 UTC by ranjan-stha

## Changes

* Update the retrieval system
* Update the chunking method.
* Update the prompts used for llm
* Update the Hyper-parameters.

## This PR doesn't introduce any:

- [X] temporary files, auto-generated files or secret keys
- [X] n+1 queries
- [X] flake8 issues
- [X] `print`
- [X] typos
- [X] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)

2024-12-20 05:54 UTC, sudan45 requested changes

2024-12-20 05:54 UTC, sudan45 commented on chatbotcore/custom_embeddings.py
> +    def embed_query(self, text: str, timeout: int = 240) -> List[float]:
lets decrease the timeout time

2024-12-20 05:54 UTC, sudan45 commented on chatbotcore/doc_loaders.py
> +        # doc_chunks = self._get_split_documents_using_token_based(documents=documents)
add note or remove the commented code

2024-12-20 07:49 UTC, ranjan-stha commented on chatbotcore/custom_embeddings.py
> +    def embed_query(self, text: str, timeout: int = 240) -> List[float]:
@sudan45 done.

2024-12-20 07:49 UTC, ranjan-stha commented on chatbotcore/doc_loaders.py
> +        # doc_chunks = self._get_split_documents_using_token_based(documents=documents)
@sudan45 done

2024-12-27 08:44 UTC, susilnem approved these changes
LGTM!

2025-01-07 05:26 UTC, sudan45 approved these changes

2025-01-07 05:31 UTC, merged